output-folder:
model-parameters: model.yaml
q-function:
    format: JSON
statespace:
     filepath: statespace.json
     generate: false
transition-map:
    save: false
training-log:
    save: true
parless:
    enabled: true
    database: SQLite.DB("archived/data/punish_data.db")
pawnn:
    enabled: true
    random-seed: 42
    initial-weights-file: ~
    weights-output-file: ~
    use-gpu: true
    cross-validate: true
    n-cv-folds: 5
    logging:
        loss: true
value-iteration:
    logging:
        mse: false
        greedy-choice-changes: true
        episode-time: true
