version: "3.9"
services:
  db:
    image: mysql:8.0.28
    restart: always
    command: --init-file /data/application/setup.sql
    environment:
      MYSQL_DATABASE: punish
      MYSQL_USER: sqlslayer
      MYSQL_PASSWORD: punish4lyfe
      MYSQL_ROOT_PASSWORD: thewoods
    volumes:
      - ./data/setup.sql:/data/application/setup.sql
      - ./data/db:/var/lib/mysql
  
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "3000:3000"
    depends_on:
      - api

  pluto-notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=my_secret_token
      - JULIA_NUM_THREADS=4
      - PLUTO_PORT=8000
    command: julia -e 'using Pluto; Pluto.run(port=8000)'
    depends_on:
      - api